area:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ; 
        s223:hasValue p:value ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Area .

tilt:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasValue p:value ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Tilt .

azimuth:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasValue p:value ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Azimuth .

cooling-COP:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Cooling ;
        s223:hasValue p:value ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:CoefficientOfPerformance . 

heating-COP:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Heating ;
        s223:hasValue p:value ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:CoefficientOfPerformance . 

cooling-capacity:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Cooling ;
        s223:hasValue p:value ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Power .

heating-capacity:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Heating ;
        s223:hasValue p:value ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Power .

temperature:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Temperature .

active-heating-stages:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:EnumeratedObservableProperty ;
        s223:hasAspect s223:Role-Heating, s223:Aspect-OperatingStatus ;
        qudt:hasUnit unit:NUM ;
        qudt:hasQuantityKind quantitykind:Count .

active-cooling-stages:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .  
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:EnumeratedObservableProperty ;
        s223:hasAspect s223:Role-Cooling, s223:Aspect-OperatingStatus ;
        qudt:hasUnit unit:NUM ;
        qudt:hasQuantityKind quantitykind:Count .

occ-heating-setpoint:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Heating, s223:Occupancy-Occupied, s223:Aspect-Setpoint ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Temperature .

occ-cooling-setpoint:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Cooling, s223:Occupancy-Occupied, s223:Aspect-Setpoint ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Temperature .

unocc-heating-setpoint:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Heating, s223:Occupancy-Unoccupied, s223:Aspect-Setpoint ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Temperature .

unocc-cooling-setpoint:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Cooling, s223:Occupancy-Unoccupied, s223:Aspect-Setpoint ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Temperature .

effective-temperature-setpoint:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Effectiveness-Active, s223:Aspect-Setpoint ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Temperature .

effective-heating-setpoint:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Heating, s223:Effectiveness-Active, s223:Aspect-Setpoint ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Temperature .

effective-cooling-setpoint:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Role-Cooling, s223:Effectiveness-Active, s223:Aspect-Setpoint ;
        qudt:hasUnit p:unit ;
        qudt:hasQuantityKind quantitykind:Temperature .

tstat-stage_count:  
  body: > 
    @prefix p: <urn:___param___#> .    
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:EnumeratedObservableProperty ;
        s223:hasAspect s223:Role-Cooling, s223:Aspect-OperatingMode ;
        s223:hasValue p:value ;
        qudt:hasUnit unit:NUM ;
        qudt:hasQuantityKind quantitykind:Count .

tstat-deadband:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Aspect-Deadband ;
        s223:hasValue p:value ;
        qudt:hasUnit p:unit ;
        qudt:isDeltaQuantity true ;
        qudt:hasQuantityKind quantitykind:Temperature .

tstat-tolerance:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasAspect s223:Aspect-Heating, s223:Aspect-Cooling, s223:Aspect-Threshold ;
        s223:hasValue p:value ;
        qudt:hasUnit p:unit ;
        qudt:isDeltaQuantity true ;
        qudt:hasQuantityKind quantitykind:Temperature .

tstat-resolution:
# Resolution in 223 is different, it is applied to properties not equipment 
# TODO: When we update how setpoints are defined for thermostats, this will have to be added as a requirement somehow
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:QuantifiableObservableProperty ;
        s223:hasValue p:value ;
        qudt:isDeltaQuantity true ;
        qudt:hasUnit p:unit .

tstat-active:
# including heating and cooling to say we can 
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    p:name a s223:EnumeratedObservableProperty ;
        s223:hasAspect s223:Aspect-Heating, s223:Aspect-Cooling, s223:Effectiveness-Active, s223:Binary-Logical ;
        s223:hasValue p:value ;
        qudt:hasUnit unit:NUM ;
    .

timezone:
# Not represented in 223P 
# Could use another ontology for this, but won't make a change for now 
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    @prefix hpf: <urn:hpflex#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    p:name a s223:EnumeratedProperty ;
        s223:hasValue p:value ;
        a hpf:Timezone ;
    .

latitude:
# Would have to use anotehr ontology for latitude, longitude, and noaastation as well. 
# latitude and longitude not in qudt, we can have in our own ontology. Makes the shape stuff a little strange
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    @prefix hpf: <urn:hpflex#> .
    p:name a s223:QuantifiableProperty ;
        s223:hasValue p:value ;
        qudt:hasUnit unit:Degree ;
        qudt:hasQuantityKind quantitykind:GeneralizedCoordinate ;
        a hpf:Latitude .

longitude:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    @prefix hpf: <urn:hpflex#> .
    p:name a s223:QuantifiableProperty ;
        s223:hasValue p:value ;
        qudt:hasUnit unit:Degree ;
        qudt:hasQuantityKind quantitykind:GeneralizedCoordinate ;
        a hpf:Longitude .

noaastation:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    @prefix hpf: <urn:hpflex#> .
    p:name a s223:EnumeratedProperty ;
        s223:hasValue p:value ;
        a hpf:NOAAStation .

volttron-external-reference:
  body: >
    @prefix p: <urn:___param___#> .
    @prefix brick: <https://brickschema.org/schema/Brick#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix quantitykind: <http://qudt.org/vocab/quantitykind/> .
    @prefix unit: <http://qudt.org/vocab/unit/> .
    @prefix hpf: <urn:hpflex#> .
    @prefix ref: <https://brickschema.org/schema/Brick/ref#> .
    p:name a s223:ExternalReference ;
        ref:hasTopicName p:ref_name ;
    .